### ISSUE TITLE
[enhancement] Add "." (dot)  symbol to radio display

### ISSUE THREAD

**Issue by CyberGuerro** [norberttak/XPanel#105]
When Selector is setted to **COM1, COM2, NAV1, NAV2** it would be useful to see on display value like "**134.90**" instead of "**13490**"

I think that it could be possible introducing a parameter in line statement
from
`line="on_select:SW_UP_COM1,dataref:sim/cockpit/radios/com1_freq_hz"`
to
`line="on_select:SW_UP_COM1,dataref:sim/cockpit/radios/com1_freq_hz,dot_position:3"`
where "**dot_position**" is the key and "**3**" is the digit after which is positioned the "**.**" symbol.

**Comment by norberttak** [comment]
I added the dot_position option. Here it is a test build for Linux: https://github.com/norberttak/XPanel/actions/runs/8910295579/artifacts/1463916654

See some details in PR #106

**Comment by CyberGuerro** [comment]
Perfect, updated my xpanel.ini files, tested and all works like expected.
Great job
