### ISSUE TITLE
Allow spaces in the configuration file

### ISSUE THREAD

**Issue by norberttak** [norberttak/XPanel#6]
The config parser shall be able to process the spaces in the configuration option lines.
At a minimum, starting a line with spaces or tabs will be valid. It can help improve the config file's readability by applying indentation.

The ideal solution would be to also allow the spaces inside the configuration lines.

**Comment by MrAnno** [comment]
Adding a lot of `\s` patterns to the config parser's regexp database would probably do the trick, but it looks relatively easy to write a real recursive descent parser for `.ini`-like syntaxes, for example:

https://www.rioki.org/2016/04/18/recusive-descent-parser.html

**Comment by norberttak** [comment]
Agree. I don't like the idea to add lots of `\s` to regexp. That's why this issue is open for so long time :-)
To be honest I plan to rewrite the whole config parser. I really don't like it in its current form. The first idea was to use BISON but it seems to be overkill for such a simple config format. The link you shared seems to be a good option. I'll read it and will think about it.
