### ISSUE TITLE
[BUG] Missing device crash the plugin and X-Plane

### ISSUE THREAD

**Issue by CyberGuerro** [norberttak/XPanel#89]
**Describe the bug**
If device specified in config (xpanel.ini) is missing (es. not connected to usb port), plugin crash and x-plane with it

**To Reproduce**
Steps to reproduce the behavior like this:
1. disconnect device
2. start x-plane
3. start fly with aircraft having xpanel.ini   (in my case Zibo 4.01.9)
4. x-plane crash

attached log file
[Log.txt](https://github.com/norberttak/XPanel/files/14613641/Log.txt)

I think that in this case plugin hasn't to crash, but when all is loaded and ready into the aircraft, something have to be write into error dialog window or better: the plugin still working ignoring missing devices informing user about it in dialog window

**Comment by CyberGuerro** [comment]
This bug can be considered close due the 1.9 version fixed it: missing devices are notified into error dialog window, without X-Plane crash.

**Comment by norberttak** [comment]
THX, I close the issue
